import Head from 'next/head';

import { ChildProps } from '~/models/types';

const MainLayout = ({ children }: ChildProps) => {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Testimonials grid section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export { MainLayout };
